"""added Sources table

Revision ID: 0df1454c0550
Revises: e730d15cd478
Create Date: 2018-09-29 20:01:48.783735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df1454c0550'
down_revision = 'e730d15cd478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=128), nullable=True),
    sa.Column('source_description', sa.String(length=1000), nullable=True),
    sa.Column('source_statistics', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_source_name'), 'source', ['source_name'], unique=False)
    op.create_index(op.f('ix_source_source_url'), 'source', ['source_url'], unique=False)
    op.add_column('article', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'source', ['source_id'], ['id'])
    op.drop_index('ix_expert_expert_name', table_name='expert')
    op.create_index(op.f('ix_expert_expert_name'), 'expert', ['expert_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_expert_name'), table_name='expert')
    op.create_index('ix_expert_expert_name', 'expert', ['expert_name'], unique=1)
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'source_id')
    op.drop_index(op.f('ix_source_source_url'), table_name='source')
    op.drop_index(op.f('ix_source_source_name'), table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###
