"""empty message

Revision ID: 94b915648262
Revises: dd41528d8ba8
Create Date: 2018-09-22 22:30:42.652645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b915648262'
down_revision = 'dd41528d8ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_fulltext', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_fulltext')
    # ### end Alembic commands ###
