"""empty message

Revision ID: dd41528d8ba8
Revises: 91351fea89da
Create Date: 2018-09-20 17:42:56.969984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd41528d8ba8'
down_revision = '91351fea89da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=True),
    sa.Column('article_author', sa.String(length=64), nullable=True),
    sa.Column('article_publishdate', sa.DateTime(), nullable=True),
    sa.Column('article_wordcount', sa.Integer(), nullable=True),
    sa.Column('article_summary', sa.String(length=1000), nullable=True),
    sa.Column('article_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_article_author'), 'article', ['article_author'], unique=False)
    op.create_index(op.f('ix_article_article_publishdate'), 'article', ['article_publishdate'], unique=False)
    op.create_index(op.f('ix_article_article_url'), 'article', ['article_url'], unique=False)
    op.create_index(op.f('ix_article_source_name'), 'article', ['source_name'], unique=False)
    op.create_table('expert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_name', sa.String(length=64), nullable=True),
    sa.Column('expert_affiliation', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_expert_affiliation'), 'expert', ['expert_affiliation'], unique=False)
    op.create_index(op.f('ix_expert_expert_name'), 'expert', ['expert_name'], unique=True)
    op.create_table('term_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=True),
    sa.Column('map_idx', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_map_map_idx'), 'term_map', ['map_idx'], unique=False)
    op.create_index(op.f('ix_term_map_term'), 'term_map', ['term'], unique=True)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=128), nullable=True),
    sa.Column('topic_genre', sa.String(length=64), nullable=True),
    sa.Column('topic_createdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_topic_createdate'), 'topic', ['topic_createdate'], unique=False)
    op.create_index(op.f('ix_topic_topic_name'), 'topic', ['topic_name'], unique=True)
    op.create_table('topic_article_at',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.create_table('topic_expert_at',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_expert_at')
    op.drop_table('topic_article_at')
    op.drop_index(op.f('ix_topic_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_topic_topic_createdate'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_term_map_term'), table_name='term_map')
    op.drop_index(op.f('ix_term_map_map_idx'), table_name='term_map')
    op.drop_table('term_map')
    op.drop_index(op.f('ix_expert_expert_name'), table_name='expert')
    op.drop_index(op.f('ix_expert_expert_affiliation'), table_name='expert')
    op.drop_table('expert')
    op.drop_index(op.f('ix_article_source_name'), table_name='article')
    op.drop_index(op.f('ix_article_article_url'), table_name='article')
    op.drop_index(op.f('ix_article_article_publishdate'), table_name='article')
    op.drop_index(op.f('ix_article_article_author'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
