"""added article title

Revision ID: e730d15cd478
Revises: 94b915648262
Create Date: 2018-09-27 23:29:17.464691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e730d15cd478'
down_revision = '94b915648262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_title', sa.String(), nullable=True))
    op.create_index(op.f('ix_article_article_title'), 'article', ['article_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_article_title'), table_name='article')
    op.drop_column('article', 'article_title')
    # ### end Alembic commands ###
